CREATE TABLE "bf_v10"."menu_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bf_v10"."menu_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"version" integer NOT NULL,
	"action" text NOT NULL,
	"changed_menu_item_id" integer,
	"items" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "menu_snapshots_version_idx" ON "bf_v10"."menu_snapshots" USING btree ("version");